<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('users')->insert([
            [
                'username' => 'ali',
                'email' => 'ali@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '70111222',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'officeuser1',
                'email' => 'office1@example.com',
                'password' => Hash::make('password123'),
                'role' => 'office_user',
                'tel' => '71122334',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen1',
                'email' => 'citizen1@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '72133445',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => 'google',
                'oauth_id' => 'google_001',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen2',
                'email' => 'citizen2@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '73144556',
                'status' => 'inactive',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'officeuser2',
                'email' => 'office2@example.com',
                'password' => Hash::make('password123'),
                'role' => 'office_user',
                'tel' => '74155667',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'elie',
                'email' => 'elie@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '75166778',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen3',
                'email' => 'citizen3@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '76177889',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => 'github',
                'oauth_id' => 'github_003',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen4',
                'email' => 'citizen4@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '77188990',
                'status' => 'inactive',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'officeuser3',
                'email' => 'office3@example.com',
                'password' => Hash::make('password123'),
                'role' => 'office_user',
                'tel' => '78199001',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => null,
                'oauth_id' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen5',
                'email' => 'citizen5@example.com',
                'password' => Hash::make('password123'),
                'role' => 'citizen',
                'tel' => '79100112',
                'status' => 'active',
                'two_factor_enabled' => false,
                'oauth_provider' => 'facebook',
                'oauth_id' => 'facebook_005',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
